repos:
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.9
    hooks:
    - id: mdformat
      additional_dependencies:
      - mdformat-tables
      - mdformat-config
      - mdformat-frontmatter
      - mdformat-gfm
